// Patches HTMLCanvasElement to return a mock WebGL2RenderingContext for
// getContext('webgl2') in jsdom. vitest-webgl-canvas-mock covers webgl and
// experimental-webgl but not webgl2; this fills that gap. Replace this file
// with a proper library if one emerges.

const GL_CONSTANTS: Record<string, number> = {
  TEXTURE_2D: 0x0de1,
  TEXTURE_MIN_FILTER: 0x2801,
  TEXTURE_MAG_FILTER: 0x2800,
  TEXTURE_WRAP_S: 0x2802,
  TEXTURE_WRAP_T: 0x2803,
  CLAMP_TO_EDGE: 0x812f,
  LINEAR: 0x2601,
  NEAREST: 0x2600,
  RGBA: 0x1908,
  UNSIGNED_BYTE: 0x1401,
  UNSIGNED_SHORT: 0x1403,
  FLOAT: 0x1406,
  UNPACK_PREMULTIPLY_ALPHA_WEBGL: 0x9157,
  ARRAY_BUFFER: 0x8892,
  ELEMENT_ARRAY_BUFFER: 0x8893,
  STATIC_DRAW: 0x88b4,
  DYNAMIC_DRAW: 0x88b8,
  TRIANGLES: 0x0004,
  VERTEX_SHADER: 0x8b31,
  FRAGMENT_SHADER: 0x8b30,
  COMPILE_STATUS: 0x8b81,
  LINK_STATUS: 0x8b82,
  BLEND: 0x0be2,
  DEPTH_TEST: 0x0b71,
  STENCIL_TEST: 0x0b90,
  CULL_FACE: 0x0b44,
  SCISSOR_TEST: 0x0c11,
  ZERO: 0,
  ONE: 1,
  SRC_ALPHA: 0x0302,
  ONE_MINUS_SRC_ALPHA: 0x0303,
  DST_ALPHA: 0x0304,
  ONE_MINUS_DST_ALPHA: 0x0305,
  COLOR_BUFFER_BIT: 0x4000,
  DEPTH_BUFFER_BIT: 0x0100,
  STENCIL_BUFFER_BIT: 0x0400,
  FRAMEBUFFER_COMPLETE: 0x8cd5,
  NO_ERROR: 0,
  COLOR_ATTACHMENT0: 0x8ce0,
  FRAMEBUFFER: 0x8d40,
  RENDERBUFFER: 0x8d41,
  DEPTH_COMPONENT16: 0x81a5,
  UNSIGNED_INT: 0x1405,
  UNSIGNED_INT_24_8: 0x84fa,
  DEPTH24_STENCIL8: 0x88f0,
  DEPTH_STENCIL: 0x84f9,
  DEPTH_STENCIL_ATTACHMENT: 0x821a,
  RGBA8: 0x8058,
  RGB8: 0x8051,
};

const GL_METHODS = [
  'activeTexture',
  'attachShader',
  'bindAttribLocation',
  'bindBuffer',
  'bindFramebuffer',
  'bindRenderbuffer',
  'bindTexture',
  'bindVertexArray',
  'blendColor',
  'blendEquation',
  'blendEquationSeparate',
  'blendFunc',
  'blendFuncSeparate',
  'bufferData',
  'bufferSubData',
  'checkFramebufferStatus',
  'clear',
  'clearBufferfv',
  'clearBufferiv',
  'clearBufferuiv',
  'clearColor',
  'clearDepth',
  'clearStencil',
  'colorMask',
  'compileShader',
  'compressedTexImage2D',
  'compressedTexSubImage2D',
  'copyTexImage2D',
  'copyTexSubImage2D',
  'createBuffer',
  'createFramebuffer',
  'createProgram',
  'createQuery',
  'createRenderbuffer',
  'createSampler',
  'createShader',
  'createTexture',
  'createTransformFeedback',
  'createVertexArray',
  'cullFace',
  'deleteBuffer',
  'deleteFramebuffer',
  'deleteProgram',
  'deleteQuery',
  'deleteRenderbuffer',
  'deleteSampler',
  'deleteShader',
  'deleteTexture',
  'deleteTransformFeedback',
  'deleteVertexArray',
  'depthFunc',
  'depthMask',
  'depthRange',
  'detachShader',
  'disable',
  'disableVertexAttribArray',
  'drawArrays',
  'drawArraysInstanced',
  'drawBuffers',
  'drawElements',
  'drawElementsInstanced',
  'drawRangeElements',
  'enable',
  'enableVertexAttribArray',
  'finish',
  'flush',
  'framebufferRenderbuffer',
  'framebufferTexture2D',
  'frontFace',
  'generateMipmap',
  'getActiveAttrib',
  'getActiveUniform',
  'getActiveUniforms',
  'getActiveUniformBlockName',
  'getActiveUniformBlockParameter',
  'getAttachedShaders',
  'getAttribLocation',
  'getBufferParameter',
  'getError',
  'getExtension',
  'getFragDataLocation',
  'getFramebufferAttachmentParameter',
  'getIndexedParameter',
  'getInternalformatParameter',
  'getParameter',
  'getProgramInfoLog',
  'getProgramParameter',
  'getQuery',
  'getQueryParameter',
  'getRenderbufferParameter',
  'getShaderInfoLog',
  'getShaderParameter',
  'getShaderPrecisionFormat',
  'getShaderSource',
  'getSupportedExtensions',
  'getTexParameter',
  'getTransformFeedbackVarying',
  'getUniform',
  'getUniformBlockIndex',
  'getUniformIndices',
  'getUniformLocation',
  'getVertexAttrib',
  'getVertexAttribOffset',
  'hint',
  'invalidateFramebuffer',
  'invalidateSubFramebuffer',
  'isBuffer',
  'isContextLost',
  'isEnabled',
  'isFramebuffer',
  'isProgram',
  'isQuery',
  'isRenderbuffer',
  'isSampler',
  'isShader',
  'isTexture',
  'isTransformFeedback',
  'isVertexArray',
  'lineWidth',
  'linkProgram',
  'pixelStorei',
  'polygonOffset',
  'readBuffer',
  'readPixels',
  'renderbufferStorage',
  'renderbufferStorageMultisample',
  'sampleCoverage',
  'samplerParameterf',
  'samplerParameteri',
  'scissor',
  'shaderSource',
  'stencilFunc',
  'stencilFuncSeparate',
  'stencilMask',
  'stencilMaskSeparate',
  'stencilOp',
  'stencilOpSeparate',
  'texImage2D',
  'texImage3D',
  'texParameterf',
  'texParameteri',
  'texStorage2D',
  'texStorage3D',
  'texSubImage2D',
  'texSubImage3D',
  'transformFeedbackVaryings',
  'uniform1f',
  'uniform1fv',
  'uniform1i',
  'uniform1iv',
  'uniform1ui',
  'uniform1uiv',
  'uniform2f',
  'uniform2fv',
  'uniform2i',
  'uniform2iv',
  'uniform2ui',
  'uniform2uiv',
  'uniform3f',
  'uniform3fv',
  'uniform3i',
  'uniform3iv',
  'uniform3ui',
  'uniform3uiv',
  'uniform4f',
  'uniform4fv',
  'uniform4i',
  'uniform4iv',
  'uniform4ui',
  'uniform4uiv',
  'uniformBlockBinding',
  'uniformMatrix2fv',
  'uniformMatrix2x3fv',
  'uniformMatrix2x4fv',
  'uniformMatrix3fv',
  'uniformMatrix3x2fv',
  'uniformMatrix3x4fv',
  'uniformMatrix4fv',
  'uniformMatrix4x2fv',
  'uniformMatrix4x3fv',
  'useProgram',
  'validateProgram',
  'vertexAttrib1f',
  'vertexAttrib1fv',
  'vertexAttrib2f',
  'vertexAttrib2fv',
  'vertexAttrib3f',
  'vertexAttrib3fv',
  'vertexAttrib4f',
  'vertexAttrib4fv',
  'vertexAttribDivisor',
  'vertexAttribI4i',
  'vertexAttribI4iv',
  'vertexAttribI4ui',
  'vertexAttribI4uiv',
  'vertexAttribIPointer',
  'vertexAttribPointer',
  'viewport',
];

function createMockWebGL2Context(): WebGL2RenderingContext {
  const ctx: Record<string, unknown> = { ...GL_CONSTANTS };
  for (const name of GL_METHODS) {
    ctx[name] = vi.fn();
  }
  (ctx.createBuffer as ReturnType<typeof vi.fn>).mockImplementation(() => ({}));
  (ctx.createFramebuffer as ReturnType<typeof vi.fn>).mockImplementation(() => ({}));
  (ctx.createProgram as ReturnType<typeof vi.fn>).mockImplementation(() => ({}));
  (ctx.createQuery as ReturnType<typeof vi.fn>).mockImplementation(() => ({}));
  (ctx.createRenderbuffer as ReturnType<typeof vi.fn>).mockImplementation(() => ({}));
  (ctx.createSampler as ReturnType<typeof vi.fn>).mockImplementation(() => ({}));
  (ctx.createShader as ReturnType<typeof vi.fn>).mockImplementation(() => ({}));
  (ctx.createTexture as ReturnType<typeof vi.fn>).mockImplementation(() => ({}));
  (ctx.createTransformFeedback as ReturnType<typeof vi.fn>).mockImplementation(() => ({}));
  (ctx.createVertexArray as ReturnType<typeof vi.fn>).mockImplementation(() => ({}));
  (ctx.checkFramebufferStatus as ReturnType<typeof vi.fn>).mockImplementation(() => GL_CONSTANTS.FRAMEBUFFER_COMPLETE);
  (ctx.getAttribLocation as ReturnType<typeof vi.fn>).mockImplementation(() => 0);
  (ctx.getError as ReturnType<typeof vi.fn>).mockImplementation(() => GL_CONSTANTS.NO_ERROR);
  (ctx.getProgramInfoLog as ReturnType<typeof vi.fn>).mockImplementation(() => '');
  (ctx.getProgramParameter as ReturnType<typeof vi.fn>).mockImplementation(() => true);
  (ctx.getShaderInfoLog as ReturnType<typeof vi.fn>).mockImplementation(() => '');
  (ctx.getShaderParameter as ReturnType<typeof vi.fn>).mockImplementation(() => true);
  (ctx.getUniformLocation as ReturnType<typeof vi.fn>).mockImplementation(() => ({}));
  (ctx.isContextLost as ReturnType<typeof vi.fn>).mockImplementation(() => false);
  return ctx as unknown as WebGL2RenderingContext;
}

const _getContext = HTMLCanvasElement.prototype.getContext;

HTMLCanvasElement.prototype.getContext = function (contextId: string, ...args: unknown[]) {
  if (contextId === 'webgl2') {
    return createMockWebGL2Context();
  }
  return (_getContext as (...a: unknown[]) => unknown).call(this, contextId, ...args);
} as typeof HTMLCanvasElement.prototype.getContext;
