import * as _vec2 from './vector2';
export {
  createVector2,
  createVector2Polar,
  vec2Add,
  vec2Clone,
  vec2Copy,
  vec2Distance,
  vec2Equals,
  vec2FromFloat32Array,
  vec2Length,
  vec2LengthSquared,
  vec2Lerp,
  vec2Normalize,
  vec2Offset,
  vec2SetPolar,
  vec2SetTo,
  vec2Subtract,
  vec2WriteToFloat32Array,
} from './vector2';
export { X_AXIS as VEC2_X_AXIS, Y_AXIS as VEC2_Y_AXIS } from './vector2';

import * as _vec3 from './vector3';
export {
  createVector3,
  vec3Add,
  vec3AngleBetween,
  vec3Clone,
  vec3Copy,
  vec3Cross,
  vec3Distance,
  vec3DistanceSquared,
  vec3Dot,
  vec3Equals,
  vec3Length,
  vec3LengthSquared,
  vec3NearEquals,
  vec3Negate,
  vec3Normalize,
  vec3Project,
  vec3Scale,
  vec3SetTo,
  vec3Subtract,
} from './vector3';
export { X_AXIS as VEC3_X_AXIS, Y_AXIS as VEC3_Y_AXIS, Z_AXIS as VEC3_Z_AXIS } from './vector3';

import * as _vec4 from './vector4';
export {
  createVector4,
  vec4Add,
  vec4AngleBetween,
  vec4Clone,
  vec4Copy,
  vec4Distance,
  vec4DistanceSquared,
  vec4Dot,
  vec4Equals,
  vec4Length,
  vec4LengthSquared,
  vec4NearEquals,
  vec4Negate,
  vec4Normalize,
  vec4Project,
  vec4Scale,
  vec4SetTo,
  vec4Subtract,
} from './vector4';
export { W_UNIT as VEC4_W_UNIT, X_AXIS as VEC4_X_AXIS, Y_AXIS as VEC4_Y_AXIS, Z_AXIS as VEC4_Z_AXIS } from './vector4';

import * as _rect from './rectangle';
export {
  createRectangle,
  rectBottom,
  rectBottomRight,
  rectClone,
  rectContains,
  rectContainsPoint,
  rectContainsRect,
  rectCopy,
  rectEquals,
  rectInflate,
  rectInflatePoint,
  rectIntersection,
  rectIntersects,
  rectIsEmpty,
  rectIsFlippedX,
  rectIsFlippedY,
  rectLeft,
  rectMaxX,
  rectMaxY,
  rectMinX,
  rectMinY,
  rectNormalize,
  rectNormalizedBottomRight,
  rectNormalizedTopLeft,
  rectOffset,
  rectOffsetPoint,
  rectRight,
  rectSetBottom,
  rectSetBottomRight,
  rectSetEmpty,
  rectSetLeft,
  rectSetRight,
  rectSetSize,
  rectSetTo,
  rectSetTop,
  rectSetTopLeft,
  rectSize,
  rectTop,
  rectTopLeft,
  rectUnion,
} from './rectangle';

import * as _mat3x2 from './matrix3x2';
export {
  createMatrix3x2,
  createMatrix3x2GradientTransform,
  createMatrix3x2Transform,
  mat3x2Clone,
  mat3x2Concat,
  mat3x2Copy,
  mat3x2CopyColumnFrom,
  mat3x2CopyColumnTo,
  mat3x2CopyRowFrom,
  mat3x2CopyRowTo,
  mat3x2Equals,
  mat3x2FromFloat32Array,
  mat3x2FromMat3x3,
  mat3x2FromMat4x4,
  mat3x2Identity,
  mat3x2Inverse,
  mat3x2InverseTransformPoint,
  mat3x2InverseTransformPointXY,
  mat3x2InverseTransformVector,
  mat3x2InverseTransformVectorXY,
  mat3x2Multiply,
  mat3x2Rotate,
  mat3x2Scale,
  mat3x2SetGradientTransform,
  mat3x2SetTo,
  mat3x2SetTransform,
  mat3x2TransformPoint,
  mat3x2TransformPointXY,
  mat3x2TransformRect,
  mat3x2TransformRectVec2,
  mat3x2TransformRectXY,
  mat3x2TransformVector,
  mat3x2TransformVectorXY,
  mat3x2Translate,
  mat3x2TranslateUsingVector,
  mat3x2TranslateUsingVectorXY,
  mat3x2WriteToFloat32Array,
} from './matrix3x2';

import * as _mat3x3 from './matrix3x3';
export {
  createMatrix3x3,
  mat3x3Clone,
  mat3x3Copy,
  mat3x3CopyColumnFrom,
  mat3x3CopyColumnTo,
  mat3x3CopyRowFrom,
  mat3x3CopyRowTo,
  mat3x3Equals,
  mat3x3FromMat3x2,
  mat3x3FromMat4x4,
  mat3x3Get,
  mat3x3Identity,
  mat3x3Inverse,
  mat3x3IsAffine,
  mat3x3Multiply,
  mat3x3Rotate,
  mat3x3Scale,
  mat3x3Set,
  mat3x3SetTo,
  mat3x3Translate,
} from './matrix3x3';

import * as _mat4x4 from './matrix4x4';
export * as matrix3x2Pool from './matrix3x2Pool';
export * as matrix3x3Pool from './matrix3x3Pool';
export {
  createMatrix4x4,
  createMatrix4x4From2D,
  createMatrix4x4Ortho,
  createMatrix4x4Perspective,
  mat4x4Append,
  mat4x4AppendRotation,
  mat4x4AppendScale,
  mat4x4AppendTranslation,
  mat4x4Clone,
  mat4x4Copy,
  mat4x4CopyColumnFrom,
  mat4x4CopyColumnTo,
  mat4x4CopyRowFrom,
  mat4x4CopyRowTo,
  mat4x4Determinant,
  mat4x4Equals,
  mat4x4FromMat3x2,
  mat4x4FromMat3x3,
  mat4x4Get,
  mat4x4Identity,
  mat4x4Interpolate,
  mat4x4Inverse,
  mat4x4IsAffine,
  mat4x4Multiply,
  mat4x4Position,
  mat4x4Prepend,
  mat4x4PrependRotation,
  mat4x4PrependScale,
  mat4x4PrependTranslation,
  mat4x4Rotate,
  mat4x4Scale,
  mat4x4Set,
  mat4x4Set2D,
  mat4x4SetOrtho,
  mat4x4SetPerspective,
  mat4x4SetPosition,
  mat4x4SetTo,
  mat4x4TransformPoint,
  mat4x4TransformVector,
  mat4x4TransformVectors,
  mat4x4Translate,
  mat4x4Transpose,
} from './matrix4x4';
export * as matrix4x4Pool from './matrix4x4Pool';
export * as rectanglePool from './rectanglePool';
export * from './typedarray';
export * as vector2Pool from './vector2Pool';
export * as vector3Pool from './vector3Pool';
export * as vector4Pool from './vector4Pool';

export const vector2 = {
  create: _vec2.createVector2,
  createPolar: _vec2.createVector2Polar,
  X_AXIS: _vec2.X_AXIS,
  Y_AXIS: _vec2.Y_AXIS,
  add: _vec2.vec2Add,
  clone: _vec2.vec2Clone,
  copy: _vec2.vec2Copy,
  distance: _vec2.vec2Distance,
  equals: _vec2.vec2Equals,
  fromFloat32Array: _vec2.vec2FromFloat32Array,
  length: _vec2.vec2Length,
  lengthSquared: _vec2.vec2LengthSquared,
  lerp: _vec2.vec2Lerp,
  normalize: _vec2.vec2Normalize,
  offset: _vec2.vec2Offset,
  setPolar: _vec2.vec2SetPolar,
  setTo: _vec2.vec2SetTo,
  subtract: _vec2.vec2Subtract,
  writeToFloat32Array: _vec2.vec2WriteToFloat32Array,
};

export const vector3 = {
  create: _vec3.createVector3,
  X_AXIS: _vec3.X_AXIS,
  Y_AXIS: _vec3.Y_AXIS,
  Z_AXIS: _vec3.Z_AXIS,
  add: _vec3.vec3Add,
  angleBetween: _vec3.vec3AngleBetween,
  clone: _vec3.vec3Clone,
  copy: _vec3.vec3Copy,
  cross: _vec3.vec3Cross,
  distance: _vec3.vec3Distance,
  distanceSquared: _vec3.vec3DistanceSquared,
  dot: _vec3.vec3Dot,
  equals: _vec3.vec3Equals,
  length: _vec3.vec3Length,
  lengthSquared: _vec3.vec3LengthSquared,
  nearEquals: _vec3.vec3NearEquals,
  negate: _vec3.vec3Negate,
  normalize: _vec3.vec3Normalize,
  project: _vec3.vec3Project,
  scale: _vec3.vec3Scale,
  setTo: _vec3.vec3SetTo,
  subtract: _vec3.vec3Subtract,
};

export const vector4 = {
  create: _vec4.createVector4,
  X_AXIS: _vec4.X_AXIS,
  Y_AXIS: _vec4.Y_AXIS,
  Z_AXIS: _vec4.Z_AXIS,
  W_UNIT: _vec4.W_UNIT,
  add: _vec4.vec4Add,
  angleBetween: _vec4.vec4AngleBetween,
  clone: _vec4.vec4Clone,
  copy: _vec4.vec4Copy,
  distance: _vec4.vec4Distance,
  distanceSquared: _vec4.vec4DistanceSquared,
  dot: _vec4.vec4Dot,
  equals: _vec4.vec4Equals,
  length: _vec4.vec4Length,
  lengthSquared: _vec4.vec4LengthSquared,
  nearEquals: _vec4.vec4NearEquals,
  negate: _vec4.vec4Negate,
  normalize: _vec4.vec4Normalize,
  project: _vec4.vec4Project,
  scale: _vec4.vec4Scale,
  setTo: _vec4.vec4SetTo,
  subtract: _vec4.vec4Subtract,
};

export const rectangle = {
  create: _rect.createRectangle,
  bottom: _rect.rectBottom,
  bottomRight: _rect.rectBottomRight,
  clone: _rect.rectClone,
  contains: _rect.rectContains,
  containsPoint: _rect.rectContainsPoint,
  containsRect: _rect.rectContainsRect,
  copy: _rect.rectCopy,
  equals: _rect.rectEquals,
  inflate: _rect.rectInflate,
  inflatePoint: _rect.rectInflatePoint,
  intersection: _rect.rectIntersection,
  intersects: _rect.rectIntersects,
  isEmpty: _rect.rectIsEmpty,
  isFlippedX: _rect.rectIsFlippedX,
  isFlippedY: _rect.rectIsFlippedY,
  left: _rect.rectLeft,
  minX: _rect.rectMinX,
  minY: _rect.rectMinY,
  maxX: _rect.rectMaxX,
  maxY: _rect.rectMaxY,
  normalize: _rect.rectNormalize,
  normalizedBottomRight: _rect.rectNormalizedBottomRight,
  normalizedTopLeft: _rect.rectNormalizedTopLeft,
  offset: _rect.rectOffset,
  offsetPoint: _rect.rectOffsetPoint,
  right: _rect.rectRight,
  setBottom: _rect.rectSetBottom,
  setBottomRight: _rect.rectSetBottomRight,
  setEmpty: _rect.rectSetEmpty,
  setLeft: _rect.rectSetLeft,
  setRight: _rect.rectSetRight,
  setSize: _rect.rectSetSize,
  setTo: _rect.rectSetTo,
  setTop: _rect.rectSetTop,
  setTopLeft: _rect.rectSetTopLeft,
  size: _rect.rectSize,
  top: _rect.rectTop,
  topLeft: _rect.rectTopLeft,
  union: _rect.rectUnion,
};

export const matrix3x2 = {
  create: _mat3x2.createMatrix3x2,
  createGradientTransform: _mat3x2.createMatrix3x2GradientTransform,
  createTransform: _mat3x2.createMatrix3x2Transform,
  clone: _mat3x2.mat3x2Clone,
  concat: _mat3x2.mat3x2Concat,
  copy: _mat3x2.mat3x2Copy,
  copyColumnFrom: _mat3x2.mat3x2CopyColumnFrom,
  copyColumnTo: _mat3x2.mat3x2CopyColumnTo,
  copyRowFrom: _mat3x2.mat3x2CopyRowFrom,
  copyRowTo: _mat3x2.mat3x2CopyRowTo,
  equals: _mat3x2.mat3x2Equals,
  fromFloat32Array: _mat3x2.mat3x2FromFloat32Array,
  fromMatrix3x3: _mat3x2.mat3x2FromMat3x3,
  fromMatrix4x4: _mat3x2.mat3x2FromMat4x4,
  identity: _mat3x2.mat3x2Identity,
  inverse: _mat3x2.mat3x2Inverse,
  inverseTransformPoint: _mat3x2.mat3x2InverseTransformPoint,
  inverseTransformPointXY: _mat3x2.mat3x2InverseTransformPointXY,
  inverseTransformVector: _mat3x2.mat3x2InverseTransformVector,
  inverseTransformVectorXY: _mat3x2.mat3x2InverseTransformVectorXY,
  multiply: _mat3x2.mat3x2Multiply,
  rotate: _mat3x2.mat3x2Rotate,
  scale: _mat3x2.mat3x2Scale,
  setGradientTransform: _mat3x2.mat3x2SetGradientTransform,
  setTo: _mat3x2.mat3x2SetTo,
  setTransform: _mat3x2.mat3x2SetTransform,
  transformPoint: _mat3x2.mat3x2TransformPoint,
  transformPointXY: _mat3x2.mat3x2TransformPointXY,
  transformRect: _mat3x2.mat3x2TransformRect,
  transformRectVec2: _mat3x2.mat3x2TransformRectVec2,
  transformRectXY: _mat3x2.mat3x2TransformRectXY,
  transformVector: _mat3x2.mat3x2TransformVector,
  transformVectorXY: _mat3x2.mat3x2TransformVectorXY,
  translate: _mat3x2.mat3x2Translate,
  translateUsingVector: _mat3x2.mat3x2TranslateUsingVector,
  translateUsingVectorXY: _mat3x2.mat3x2TranslateUsingVectorXY,
  writeToFloat32Array: _mat3x2.mat3x2WriteToFloat32Array,
};

export const matrix3x3 = {
  create: _mat3x3.createMatrix3x3,
  clone: _mat3x3.mat3x3Clone,
  copy: _mat3x3.mat3x3Copy,
  copyColumnFrom: _mat3x3.mat3x3CopyColumnFrom,
  copyColumnTo: _mat3x3.mat3x3CopyColumnTo,
  copyRowFrom: _mat3x3.mat3x3CopyRowFrom,
  copyRowTo: _mat3x3.mat3x3CopyRowTo,
  equals: _mat3x3.mat3x3Equals,
  fromMatrix3x2: _mat3x3.mat3x3FromMat3x2,
  fromMatrix4x4: _mat3x3.mat3x3FromMat4x4,
  get: _mat3x3.mat3x3Get,
  identity: _mat3x3.mat3x3Identity,
  inverse: _mat3x3.mat3x3Inverse,
  isAffine: _mat3x3.mat3x3IsAffine,
  multiply: _mat3x3.mat3x3Multiply,
  rotate: _mat3x3.mat3x3Rotate,
  scale: _mat3x3.mat3x3Scale,
  set: _mat3x3.mat3x3Set,
  setTo: _mat3x3.mat3x3SetTo,
  translate: _mat3x3.mat3x3Translate,
};

export const matrix4x4 = {
  create: _mat4x4.createMatrix4x4,
  create2D: _mat4x4.createMatrix4x4From2D,
  createOrtho: _mat4x4.createMatrix4x4Ortho,
  createPerspective: _mat4x4.createMatrix4x4Perspective,
  append: _mat4x4.mat4x4Append,
  appendRotation: _mat4x4.mat4x4AppendRotation,
  appendScale: _mat4x4.mat4x4AppendScale,
  appendTranslation: _mat4x4.mat4x4AppendTranslation,
  clone: _mat4x4.mat4x4Clone,
  copy: _mat4x4.mat4x4Copy,
  copyColumnFrom: _mat4x4.mat4x4CopyColumnFrom,
  copyColumnTo: _mat4x4.mat4x4CopyColumnTo,
  copyRowFrom: _mat4x4.mat4x4CopyRowFrom,
  copyRowTo: _mat4x4.mat4x4CopyRowTo,
  determinant: _mat4x4.mat4x4Determinant,
  equals: _mat4x4.mat4x4Equals,
  fromMatrix3x2: _mat4x4.mat4x4FromMat3x2,
  fromMatrix3x3: _mat4x4.mat4x4FromMat3x3,
  get: _mat4x4.mat4x4Get,
  identity: _mat4x4.mat4x4Identity,
  interpolate: _mat4x4.mat4x4Interpolate,
  inverse: _mat4x4.mat4x4Inverse,
  isAffine: _mat4x4.mat4x4IsAffine,
  multiply: _mat4x4.mat4x4Multiply,
  position: _mat4x4.mat4x4Position,
  prepend: _mat4x4.mat4x4Prepend,
  prependRotation: _mat4x4.mat4x4PrependRotation,
  prependScale: _mat4x4.mat4x4PrependScale,
  prependTranslation: _mat4x4.mat4x4PrependTranslation,
  rotate: _mat4x4.mat4x4Rotate,
  scale: _mat4x4.mat4x4Scale,
  set: _mat4x4.mat4x4Set,
  set2D: _mat4x4.mat4x4Set2D,
  setOrtho: _mat4x4.mat4x4SetOrtho,
  setPerspective: _mat4x4.mat4x4SetPerspective,
  setPosition: _mat4x4.mat4x4SetPosition,
  setTo: _mat4x4.mat4x4SetTo,
  transformPoint: _mat4x4.mat4x4TransformPoint,
  transformVector: _mat4x4.mat4x4TransformVector,
  transformVectors: _mat4x4.mat4x4TransformVectors,
  translate: _mat4x4.mat4x4Translate,
  transpose: _mat4x4.mat4x4Transpose,
};
